server:
  address: 0.0.0.0
  port: 10001
  sessionTimeout: 3600

spring:
  application:
    name: ${artifactId}
    index: /

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.59.206:3306/qarphql?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Yang123456!qazwsx

#graphql:
#  servlet:
#    mapping: /resources/graphql
#    enabled: true
#    corsEnabled: true
